# Downloads Let's Encrypt intermediate certificates and updates lib/config/letsencrypt_certs.dart
# Run: .\scripts\update_letsencrypt_certs.ps1
# Requires: PowerShell 5+ and network access

$ErrorActionPreference = "Stop"
# TLS 1.2 required for letsencrypt.org
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$certUrls = @(
    @{ Name = "E7"; Url = "https://letsencrypt.org/certs/2024/e7.pem" },
    @{ Name = "R12"; Url = "https://letsencrypt.org/certs/2024/r12.pem" },
    @{ Name = "YE1"; Url = "https://letsencrypt.org/certs/gen-y/int-ye1.pem" },
    @{ Name = "YE2"; Url = "https://letsencrypt.org/certs/gen-y/int-ye2.pem" },
    @{ Name = "YR1"; Url = "https://letsencrypt.org/certs/gen-y/int-yr1.pem" },
    @{ Name = "YR2"; Url = "https://letsencrypt.org/certs/gen-y/int-yr2.pem" }
)

$certs = @{}
foreach ($c in $certUrls) {
    try {
        Write-Host "Fetching $($c.Name)..."
        $response = Invoke-WebRequest -Uri $c.Url -UseBasicParsing
        $content = if ($response.Content -is [string]) { $response.Content } else { [System.Text.Encoding]::UTF8.GetString($response.Content) }
        $certs[$c.Name] = $content.Trim()
        Write-Host "  OK"
    } catch {
        Write-Warning "  Failed to fetch $($c.Name): $_"
    }
}

if ($certs.Count -eq 0) {
    Write-Host ""
    Write-Host "Could not fetch certificates automatically. Please download manually:"
    Write-Host "  1. Open https://letsencrypt.org/certificates/"
    Write-Host "  2. Download E7, R12 (2024), and YE1, YE2, YR1, YR2 (Gen Y) PEMs"
    Write-Host "  3. Add them to lib/config/letsencrypt_certs.dart"
    Write-Host ""
    Write-Host "Or run with Git Bash: curl -o e7.pem https://letsencrypt.org/certs/2024/e7.pem"
    exit 1
}

$dartPath = Join-Path $PSScriptRoot "..\lib\config\letsencrypt_certs.dart"

$content = @"
/// Let's Encrypt intermediate certificates for pinning.
/// Auto-generated by scripts/update_letsencrypt_certs.ps1
/// Run the script to update when Let's Encrypt rotates intermediates.
/// E7, R12: valid to 2027. YE1, YE2, YR1, YR2: valid to 2028.
"@

foreach ($name in $certs.Keys | Sort-Object) {
    $pem = $certs[$name]
    $escaped = $pem -replace '\\', '\\\\' -replace "`r`n", "\n" -replace "`n", "\n"
    $content += "`n`nconst String letsEncrypt${name}Pem = '''`n$pem`n''';"
}

$content += @"

/// All current intermediates (concatenated for SecurityContext)
const List<String> letsEncryptAllPems = [
"@

foreach ($name in $certs.Keys | Sort-Object) {
    $content += "  letsEncrypt${name}Pem,`n"
}

$content += @"
];
"@

Set-Content -Path $dartPath -Value $content -Encoding UTF8
Write-Host "`nUpdated $dartPath with $($certs.Count) certificate(s)"
Write-Host "Run 'flutter pub get' and rebuild the app."
